volumes:
  db:
  nextcloud:

services:
  db:
    image: docker.io/library/mariadb:10.5
    expose:
    - "3306"
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=
      - MARIADB_PASSWORD=
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
      - MARIADB_PASSWORD=nextcloud
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true

  # Console is available at URL: http://localhost:8080/login?direct=1
  # Do not forget to disable https in the Nextcloud config
  # podman exec -it -u www-data recettes-hellofresh_nextcloud_1 ./occ config:system:set --type string --value http overwriteprotocol
  nextcloud:
    image: docker.io/library/nextcloud:23-fpm-alpine
    restart: always
    expose:
      - "9000"
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=secret
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - NEXTCLOUD_TRUSTED_DOMAINS=host.dns.host

  nginx:
    image: docker.io/library/nginx:1.23-alpine
    restart: always
    ports:
    - "8080:8080"
    links:
      - nextcloud
    volumes:
      - nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - nextcloud:/var/www/html

  collabora:
    image: docker.io/collabora/code:22.05.9.2.1
    ports:
    - "9980:9980"
    cap_add:
    - MKNOD
    environment:
    - username=admin
    - password=secret
    - DONT_GEN_SSL_CERT=true
    - server_name=host.dns.host:9980
    - aliasgroup1=http://host.dns.host:8080
    - dictionaries=en_GB en_US fr_FR
    - extra_params=--o:ssl.enable=false
    links:
      - nextcloud
